# Generated by Django 2.2.4 on 2019-11-16 20:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20191116_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='comment_article', to='articles.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 20, 58, 48, 741832, tzinfo=utc), verbose_name='date'),
        ),
    ]
