# Generated by Django 2.2.4 on 2019-11-16 20:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20191116_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 20, 59, 22, 145768, tzinfo=utc), verbose_name='date'),
        ),
    ]
