# Generated by Django 2.2.4 on 2019-11-16 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20191116_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
