# Generated by Django 2.2.7 on 2019-11-26 18:27

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20191121_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=djrichtextfield.models.RichTextField(verbose_name='post text'),
        ),
    ]
