# Generated by Django 2.2.7 on 2019-11-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_auto_20191126_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.TextField(verbose_name='post text'),
        ),
    ]
