# Generated by Django 2.2.7 on 2019-11-26 20:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_auto_20191126_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='post text'),
        ),
    ]
